name: ${SD_WP_LANDO_APP_NAME} ######## ⚠️PLEASE CHANGE THIS TO YOUR AWESOME APP's NAME!⚠️
recipe: wordpress
config:
  via: nginx
  php: 7.4
  webroot: wordpress
  database: mariadb
  xdebug: true
  config:
    php: .lando/php.ini
    vhosts: .lando/nginx.conf
services:
  rediscache:
    type: redis
  mailhog:
    type: mailhog
    portforward: false
    hogfrom:
      - appserver
  appserver:
    overrides:
      environment:
        # Make this environment variable empty or else runtime xdebug mode change will not work
        XDEBUG_MODE: ''
        # Support debugging Drush with XDEBUG.
        PHP_IDE_CONFIG: "serverName=appserver"
        PROFILER_OUTPUT_DIR: "profiler-output" # If changing this value, change in .gitignore also
      volumes:
        # LINK CORE FILES. DON'T LINK THE ENTIRE DIRECTORY, BECAUSE THAT CAN CAUSE MANY IMPORTANT CORE LOCAL FILES TO BE OVERRIDDEN.
        - '~/wordpress/wordpress.setup-DO-NOT-DELETE/wordpress-core/wp-admin:/app/wordpress/wp-admin'
        - '~/wordpress/wordpress.setup-DO-NOT-DELETE/wordpress-core/wp-includes:/app/wordpress/wp-includes'
        - '~/wordpress/wordpress.setup-DO-NOT-DELETE/wordpress-core:/app/wordpress/index.php'
        - '~/wordpress/wordpress.setup-DO-NOT-DELETE/wordpress-core/wp-activate.php:/app/wordpress/wp-activate.php'
        - '~/wordpress/wordpress.setup-DO-NOT-DELETE/wordpress-core/wp-blog-header.php:/app/wordpress/wp-blog-header.php'
        - '~/wordpress/wordpress.setup-DO-NOT-DELETE/wordpress-core/wp-comments-post.php:/app/wordpress/wp-comments-post.php'
        - '~/wordpress/wordpress.setup-DO-NOT-DELETE/wordpress-core/wp-cron.php:/app/wordpress/wp-cron.php'
        - '~/wordpress/wordpress.setup-DO-NOT-DELETE/wordpress-core/wp-links-opml.php:/app/wordpress/wp-links-opml.php'
        - '~/wordpress/wordpress.setup-DO-NOT-DELETE/wordpress-core/wp-load.php:/app/wordpress/wp-load.php'
        - '~/wordpress/wordpress.setup-DO-NOT-DELETE/wordpress-core/wp-login.php:/app/wordpress/wp-login.php'
        - '~/wordpress/wordpress.setup-DO-NOT-DELETE/wordpress-core/wp-mail.php:/app/wordpress/wp-mail.php'
        - '~/wordpress/wordpress.setup-DO-NOT-DELETE/wordpress-core/wp-settings.php:/app/wordpress/wp-settings.php'
        - '~/wordpress/wordpress.setup-DO-NOT-DELETE/wordpress-core/wp-signup.php:/app/wordpress/wp-signup.php'
        - '~/wordpress/wordpress.setup-DO-NOT-DELETE/wordpress-core/wp-trackback.php:/app/wordpress/wp-trackback.php'
        - '~/wordpress/wordpress.setup-DO-NOT-DELETE/wordpress-core/xmlrpc.php:/app/wordpress/xmlrpc.php'
        - '~/wordpress/wordpress.setup-DO-NOT-DELETE/wordpress-core:/app/wordpress'
        # LINK LANDO CONFIG FILES.
        - '.lando/wp-cli.yml:/wp-cli.yml'
        # LINK WP-CONTENT DIRECTORY.
        - './wp-content:/app/wordpress/wp-content'
        # LINK WP-CONFIG.PHP FILE.
        - './wp-config.php:/app/wordpress/wp-config.php'
    # Not needed because we are creating having wordpress-core already downloaded.
    # build:
    #   - wp core download --version=5.8.3 --force --skip-content
    run:
      - sleep 2 # For some reason, we have to wait at least a second till database is up.
      - | # Create WordPress config file and add necessary constants and custom config
        wp config create --dbhost=database --dbname=wordpress --dbuser=wordpress --dbpass=wordpress --dbprefix=wp_ --force --extra-php <<PHP
        \$redis_server = array(
            'host'     => 'rediscache',
            'port'     => 6379,
        );
        PHP
      - wp config set WP_DEBUG true --raw
      - wp config set WP_DEBUG_LOG true --raw
      - wp config set WP_DEBUG_DISPLAY true --raw
      - wp config set AUTOMATIC_UPDATER_DISABLED true --raw
      - wp config set DISALLOW_FILE_EDIT false --raw
      - wp config set WP_ENVIRONMENT_TYPE 'local'
      - | # Let's check if WordPress is not installed, then install it
        if ! wp core is-installed; then
          wp core install --url=https://$LANDO_APP_NAME.$LANDO_DOMAIN \
            --title=$LANDO_APP_NAME \
            --admin_user=admin \
            --admin_password=admin \
            --admin_email=admin@souptik2001.com \
            --skip-email
          wp plugin activate query-monitor
        fi
tooling:
  xdebug:
    description: Loads Xdebug in the selected mode.
    cmd:
      - appserver: /app/.lando/xdebug.sh
    user: root